/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Run the graph and return a complete response.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Session */
        delete: operations["clear_session_api_v1_chat_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/session/{session_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_v1_chat_session__session_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List every session the calling token owns, newest first.
         *
         *     Sessions with no recorded meta (e.g. claimed before this feature shipped)
         *     are returned with a placeholder title so the UI can still show them; their
         *     timestamp is the message-key creation time, which is best-effort.
         */
        get: operations["list_sessions_api_v1_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Stream graph progress and model tokens as Server-Sent Events.
         */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["list_chunks_api_v1_documents_chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Documents
         * @description Drop every passage in every base. Base names and descriptions survive.
         *
         *     Kept for operations and tests; the UI removes one base at a time, which is
         *     what a user actually wants and does not require re-creating the bases they
         *     still intend to keep.
         */
        delete: operations["clear_documents_api_v1_documents_clear_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Knowledge Bases
         * @description Every base, with its passage and file counts.
         *
         *     Counts are aggregated in one metadata sweep rather than a query per base, so
         *     the sidebar renders from a single round trip.
         */
        get: operations["list_knowledge_bases_api_v1_documents_knowledge_bases_get"];
        put?: never;
        /** Create Knowledge Base */
        post: operations["create_knowledge_base_api_v1_documents_knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/knowledge-bases/{kb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Knowledge Base
         * @description Delete a base and every passage in it.
         */
        delete: operations["delete_knowledge_base_api_v1_documents_knowledge_bases__kb_id__delete"];
        options?: never;
        head?: never;
        /** Update Knowledge Base */
        patch: operations["update_knowledge_base_api_v1_documents_knowledge_bases__kb_id__patch"];
        trace?: never;
    };
    "/api/v1/documents/knowledge-bases/{kb_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Knowledge Base
         * @description Remove every passage in one base, keeping the base itself.
         *
         *     Needed because the built-in base cannot be deleted — without this, the
         *     sample corpus that ships with the project could never be cleared out.
         */
        delete: operations["clear_knowledge_base_api_v1_documents_knowledge_bases__kb_id__documents_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_documents_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Text */
        post: operations["upload_text_api_v1_documents_upload_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** Doc Type */
            doc_type?: string | null;
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Knowledge Base Id
             * @default default
             */
            knowledge_base_id: string;
        };
        /** Body_upload_text_api_v1_documents_upload_text_post */
        Body_upload_text_api_v1_documents_upload_text_post: {
            /** Content */
            content: string;
            /**
             * Doc Type
             * @default markdown
             */
            doc_type: string;
            /**
             * Knowledge Base Id
             * @default default
             */
            knowledge_base_id: string;
            /**
             * Source
             * @default manual_input
             */
            source: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Knowledge Base Ids
             * @description Knowledge bases this question may draw on. Omit — or send an empty list — to search every base.
             */
            knowledge_base_ids?: string[] | null;
            /** Query */
            query: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Intent */
            intent: string;
            /** Is Valid */
            is_valid: boolean;
            /** Iteration */
            iteration: number;
            /** Query */
            query: string;
            /** Response */
            response: string;
            /** Retrieved Count */
            retrieved_count: number;
            /** Session Id */
            session_id: string;
            /**
             * Sources
             * @description Distinct documents behind this answer, most relevant first
             */
            sources?: components["schemas"]["SourceRef"][];
            /** Validation Reason */
            validation_reason: string;
        };
        /** ChunkItem */
        ChunkItem: {
            /** Content */
            content: string;
            /** Id */
            id: string;
            /** Kb Id */
            kb_id: string;
            /** Source */
            source: string;
            /** Type */
            type: string;
        };
        /** DocumentStatsResponse */
        DocumentStatsResponse: {
            /** Collection Name */
            collection_name: string;
            /** Knowledge Base Count */
            knowledge_base_count: number;
            /** Knowledge Base Id */
            knowledge_base_id?: string | null;
            /** Total Documents */
            total_documents: number;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /** Chunks Added */
            chunks_added: number;
            /**
             * File Id
             * @description Content-addressed id: re-uploading identical bytes yields the same value
             */
            file_id: string;
            /** Filename */
            filename: string;
            /** Knowledge Base Id */
            knowledge_base_id: string;
            /** Knowledge Base Name */
            knowledge_base_name: string;
            /** Status */
            status: string;
            /** Total Docs */
            total_docs: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
            /** Status */
            status: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /** KnowledgeBaseCreate */
        KnowledgeBaseCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** KnowledgeBaseInfo */
        KnowledgeBaseInfo: {
            /**
             * Chunk Count
             * @description Indexed passages in this base
             * @default 0
             */
            chunk_count: number;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Document Count
             * @description Distinct source files in this base
             * @default 0
             */
            document_count: number;
            /** Id */
            id: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Name */
            name: string;
        };
        /** KnowledgeBaseUpdate */
        KnowledgeBaseUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * ServiceStatus
         * @description Per-dependency probe result.
         *
         *     A loose ``dict`` would publish an empty schema, leaving clients with no
         *     contract at all. Declaring the fields keeps the health payload typed while
         *     ``response_model_exclude_none`` keeps the wire format unchanged.
         */
        ServiceStatus: {
            /** Api Key Set */
            api_key_set?: boolean | null;
            /** Backend */
            backend?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Doc Count */
            doc_count?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Error */
            error?: string | null;
            /** Model */
            model?: string | null;
            /** Status */
            status: string;
        };
        /** SessionSummary */
        SessionSummary: {
            /** Created At */
            created_at: number;
            /** Message Count */
            message_count: number;
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: number;
        };
        /** SourceRef */
        SourceRef: {
            /**
             * Document
             * @description File the passage came from
             */
            document: string;
            /** Knowledge Base Id */
            knowledge_base_id: string;
            /** Knowledge Base Name */
            knowledge_base_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_session_api_v1_chat_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_chat_session__session_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_api_v1_documents_chunks_get: {
        parameters: {
            query?: {
                knowledge_base_id?: string | null;
                limit?: number;
            };
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_documents_api_v1_documents_clear_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_bases_api_v1_documents_knowledge_bases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseInfo"][];
                };
            };
        };
    };
    create_knowledge_base_api_v1_documents_knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_base_api_v1_documents_knowledge_bases__kb_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_knowledge_base_api_v1_documents_knowledge_bases__kb_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_knowledge_base_api_v1_documents_knowledge_bases__kb_id__documents_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_documents_stats_get: {
        parameters: {
            query?: {
                knowledge_base_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_text_api_v1_documents_upload_text_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_upload_text_api_v1_documents_upload_text_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
